/**
 * @typedef {import('./types').SearchResult} SearchResult
 * 30 realistic mock research entries
 */

/** @type {SearchResult[]} */
export const MOCK_RESULTS = [
  {
    id: '1',
    type: 'journal_article',
    title: 'Attention Is All You Need: Transformers and the Paradigm Shift in Neural Machine Translation',
    authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit', 'Llion Jones'],
    venue: 'Advances in Neural Information Processing Systems (NeurIPS)',
    year: 2017,
    citationCount: 87421,
    citationTrend: [4200, 6100, 9800, 14200, 18900, 24100, 31200],
    abstract: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
    tags: ['Deep Learning', 'Natural Language Processing', 'Attention Mechanism', 'Neural Networks'],
  },
  {
    id: '2',
    type: 'conference_paper',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
    authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
    venue: 'NAACL-HLT 2019',
    year: 2019,
    citationCount: 62345,
    citationTrend: [3100, 7200, 12400, 18600, 22100, 28900, 34500],
    abstract: 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.',
    tags: ['NLP', 'BERT', 'Pre-training', 'Transfer Learning'],
  },
  {
    id: '3',
    type: 'journal_article',
    title: 'Deep Residual Learning for Image Recognition',
    authors: ['Kaiming He', 'Xiangyu Zhang', 'Shaoqing Ren', 'Jian Sun'],
    venue: 'IEEE Conference on Computer Vision and Pattern Recognition (CVPR)',
    year: 2016,
    citationCount: 148920,
    citationTrend: [12000, 21000, 32000, 48000, 62000, 81000, 101000],
    abstract: 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions.',
    tags: ['Computer Vision', 'Deep Learning', 'ResNet', 'Image Classification'],
  },
  {
    id: '4',
    type: 'preprint',
    title: 'GPT-4 Technical Report: A Large Multimodal Model with Human-Level Performance on Benchmarks',
    authors: ['OpenAI', 'Josh Achiam', 'Steven Adler', 'Sandhini Agarwal'],
    venue: 'arXiv Preprint',
    year: 2023,
    citationCount: 18420,
    citationTrend: [1200, 2800, 4100, 6200, 9100, 13400, 16900],
    abstract: 'We report the development of GPT-4, a large-scale, multimodal model which can accept image and text inputs and produce text outputs. While less capable than humans in many real-world scenarios, GPT-4 exhibits human-level performance on various professional and academic benchmarks.',
    tags: ['Large Language Models', 'GPT-4', 'Multimodal AI', 'Generative AI'],
  },
  {
    id: '5',
    type: 'journal_article',
    title: 'ImageNet Large Scale Visual Recognition Challenge',
    authors: ['Olga Russakovsky', 'Jia Deng', 'Hao Su', 'Jonathan Krause', 'Sanjeev Satheesh', 'Sean Ma'],
    venue: 'International Journal of Computer Vision (IJCV)',
    year: 2015,
    citationCount: 42800,
    citationTrend: [2800, 5100, 8900, 13400, 18200, 26100, 31800],
    abstract: 'The ImageNet Large Scale Visual Recognition Challenge (ILSVRC) is a benchmark in object category classification and detection on hundreds of object categories and millions of images. The challenge has been running annually since 2010 and has played a central role in advancing computer vision research.',
    tags: ['Computer Vision', 'Benchmarks', 'Object Detection', 'ImageNet'],
  },
  {
    id: '6',
    type: 'conference_paper',
    title: 'Generative Adversarial Networks',
    authors: ['Ian J. Goodfellow', 'Jean Pouget-Abadie', 'Mehdi Mirza', 'Bing Xu', 'David Warde-Farley'],
    venue: 'Advances in Neural Information Processing Systems (NeurIPS)',
    year: 2014,
    citationCount: 61230,
    citationTrend: [4100, 8700, 14200, 21500, 31200, 43900, 55100],
    abstract: 'We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data rather than G.',
    tags: ['GANs', 'Generative Models', 'Deep Learning', 'Unsupervised Learning'],
  },
  {
    id: '7',
    type: 'thesis',
    title: 'Learning Representations by Backpropagating Errors: A Historical Analysis and Modern Applications',
    authors: ['Sarah Chen'],
    venue: 'MIT Department of Computer Science',
    year: 2022,
    citationCount: 342,
    citationTrend: [12, 28, 56, 102, 198, 267, 342],
    abstract: 'This thesis provides a comprehensive historical analysis of backpropagation algorithms and their modern applications in training deep neural networks. We trace the evolution from the 1986 seminal paper to contemporary applications in large-scale language models and vision systems.',
    tags: ['Backpropagation', 'Neural Networks', 'Optimization', 'History of AI'],
  },
  {
    id: '8',
    type: 'patent',
    title: 'System and Method for Training Large-Scale Neural Networks with Gradient Checkpointing',
    authors: ['Yoshua Bengio', 'Aaron Courville', 'Pascal Vincent'],
    venue: 'US Patent Office',
    year: 2021,
    citationCount: 156,
    citationTrend: [8, 22, 45, 78, 112, 134, 156],
    abstract: 'A system and method for efficient training of large-scale neural networks using gradient checkpointing to reduce memory consumption. The method selectively stores intermediate activations during forward pass and recomputes them during backward pass, enabling training on hardware with limited memory.',
    tags: ['Neural Network Training', 'Memory Optimization', 'Patent', 'Gradient Checkpointing'],
  },
  {
    id: '9',
    type: 'journal_article',
    title: 'Human-level control through deep reinforcement learning',
    authors: ['Volodymyr Mnih', 'Koray Kavukcuoglu', 'David Silver', 'Andrei A. Rusu'],
    venue: 'Nature',
    year: 2015,
    citationCount: 32180,
    citationTrend: [2100, 4800, 8100, 12900, 18400, 24600, 29800],
    abstract: 'We use recent advances in training deep neural networks to develop a novel artificial agent, termed a deep Q-network, that can learn successful policies directly from high-dimensional sensory inputs using end-to-end reinforcement learning. We tested this agent on the challenging domain of classic Atari 2600 games.',
    tags: ['Reinforcement Learning', 'DQN', 'Atari', 'Deep Q-Network'],
  },
  {
    id: '10',
    type: 'conference_paper',
    title: 'Masked Autoencoders Are Scalable Vision Learners',
    authors: ['Kaiming He', 'Xinlei Chen', 'Saining Xie', 'Yanghao Li', 'Piotr Dollar'],
    venue: 'CVPR 2022',
    year: 2022,
    citationCount: 9841,
    citationTrend: [420, 1100, 2400, 4100, 6200, 8100, 9841],
    abstract: 'This paper shows that masked autoencoders (MAE) are scalable self-supervised learners for computer vision. Our MAE approach is simple: we mask random patches of the input image and reconstruct the missing pixels. It is based on two core designs.',
    tags: ['Self-supervised Learning', 'MAE', 'Vision Transformers', 'Computer Vision'],
  },
  {
    id: '11',
    type: 'journal_article',
    title: 'CRISPR-Cas9 for medical genetic screens: progress and future prospects',
    authors: ['Feng Zhang', 'Jennifer Doudna', 'Emmanuelle Charpentier'],
    venue: 'Nature Reviews Genetics',
    year: 2020,
    citationCount: 7821,
    citationTrend: [512, 1100, 2200, 3800, 5100, 6600, 7821],
    abstract: 'CRISPR-based genomic screens have become powerful tools for functional genomics and drug target discovery. Recent advances have enabled genome-scale pooled screens, arrayed screens, and single-cell transcriptome-linked screens, each with unique advantages and challenges.',
    tags: ['CRISPR', 'Gene Editing', 'Genomics', 'Biotechnology'],
  },
  {
    id: '12',
    type: 'preprint',
    title: 'LLaMA: Open and Efficient Foundation Language Models for Reasoning Tasks',
    authors: ['Hugo Touvron', 'Thibaut Lavril', 'Gautier Izacard', 'Xavier Martinet'],
    venue: 'arXiv Preprint',
    year: 2023,
    citationCount: 12340,
    citationTrend: [800, 1900, 3400, 5700, 8100, 10200, 12340],
    abstract: 'We introduce LLaMA, a collection of foundation language models ranging from 7B to 65B parameters. We train our models on trillions of tokens, and show that it is possible to train state-of-the-art models using publicly available datasets exclusively.',
    tags: ['Large Language Models', 'LLaMA', 'Open Source AI', 'Foundation Models'],
  },
  {
    id: '13',
    type: 'book_chapter',
    title: 'Graph Neural Networks: A Review of Methods and Applications',
    authors: ['Jie Zhou', 'Ganqu Cui', 'Shengding Hu', 'Zhengyan Zhang'],
    venue: 'Deep Learning on Graphs — Cambridge University Press',
    year: 2020,
    citationCount: 4321,
    citationTrend: [210, 560, 1100, 1900, 2700, 3600, 4321],
    abstract: 'Graph Neural Networks (GNNs) are connectionist models that capture the dependence of graphs via message passing between the nodes of graphs. Unlike standard neural networks, graph neural networks retain a state that can represent information from its neighborhood with arbitrary depth.',
    tags: ['Graph Neural Networks', 'GNNs', 'Graph Learning', 'Deep Learning'],
  },
  {
    id: '14',
    type: 'conference_paper',
    title: 'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale',
    authors: ['Alexey Dosovitskiy', 'Lucas Beyer', 'Alexander Kolesnikov', 'Dirk Weissenborn'],
    venue: 'ICLR 2021',
    year: 2021,
    citationCount: 28940,
    citationTrend: [1800, 4200, 7900, 12800, 18100, 23600, 28940],
    abstract: 'While the Transformer architecture has become the de-facto standard for natural language processing tasks, its applications to computer vision remain limited. In vision, attention is either applied in conjunction with convolutional networks, or used to replace certain components of convolutional networks while keeping their overall structure in place.',
    tags: ['Vision Transformer', 'ViT', 'Image Recognition', 'Attention Mechanism'],
  },
  {
    id: '15',
    type: 'journal_article',
    title: 'Quantum Computing and its Applications in Drug Discovery: A Systematic Review',
    authors: ['Maria Santos', 'Ricardo Ferreira', 'Claudia Martins', 'Paulo Alves'],
    venue: 'Journal of Computational Chemistry',
    year: 2023,
    citationCount: 892,
    citationTrend: [42, 118, 234, 412, 598, 742, 892],
    abstract: 'Quantum computing has emerged as a transformative technology with the potential to revolutionize drug discovery by enabling the simulation of molecular systems at quantum mechanical precision. This systematic review analyzes recent progress in quantum algorithms for molecular simulation.',
    tags: ['Quantum Computing', 'Drug Discovery', 'Computational Chemistry', 'Molecular Simulation'],
  },
  {
    id: '16',
    type: 'journal_article',
    title: 'AlphaFold: Highly accurate protein structure prediction with deep learning',
    authors: ['John Jumper', 'Richard Evans', 'Alexander Pritzel', 'Tim Green', 'Michael Figurnov'],
    venue: 'Nature',
    year: 2021,
    citationCount: 19820,
    citationTrend: [1200, 3400, 6800, 10200, 13900, 17100, 19820],
    abstract: 'Predicting a protein\'s structure from its primary sequence has been a grand challenge in biology for the past 50 years. We introduce AlphaFold, an attention-based neural network architecture trained end-to-end that predicts protein structure with atomic accuracy even in cases where no similar structure is known.',
    tags: ['Protein Folding', 'AlphaFold', 'Bioinformatics', 'Deep Learning'],
  },
  {
    id: '17',
    type: 'conference_paper',
    title: 'Diffusion Models Beat GANs on Image Synthesis',
    authors: ['Prafulla Dhariwal', 'Alexander Quinn Nichol'],
    venue: 'NeurIPS 2021',
    year: 2021,
    citationCount: 8930,
    citationTrend: [480, 1200, 2500, 4100, 5900, 7400, 8930],
    abstract: 'We show that diffusion models can achieve image sample quality superior to the current state-of-the-art generative models. We achieve this on unconditional image synthesis by finding a better architecture through a series of ablations. For conditional image synthesis, we further improve sample quality with classifier guidance.',
    tags: ['Diffusion Models', 'Generative Models', 'Image Synthesis', 'GANs'],
  },
  {
    id: '18',
    type: 'patent',
    title: 'Method for Real-time Federated Learning in Edge Computing Environments',
    authors: ['Liping Wei', 'Thomas Mueller', 'Priya Sharma'],
    venue: 'European Patent Office',
    year: 2022,
    citationCount: 78,
    citationTrend: [5, 14, 28, 42, 58, 68, 78],
    abstract: 'This invention describes a method and system for performing real-time federated learning across distributed edge computing nodes while preserving data privacy. The method enables collaborative model training without sharing raw data, using secure aggregation protocols.',
    tags: ['Federated Learning', 'Edge Computing', 'Privacy', 'Distributed AI'],
  },
  {
    id: '19',
    type: 'journal_article',
    title: 'Self-supervised Learning: Generative or Contrastive',
    authors: ['Xiao Liu', 'Fanjin Zhang', 'Zhenyu Hou', 'Li Mian', 'Zhaoyu Wang'],
    venue: 'IEEE Transactions on Knowledge and Data Engineering',
    year: 2023,
    citationCount: 3241,
    citationTrend: [180, 480, 910, 1600, 2200, 2800, 3241],
    abstract: 'Self-supervised learning has become a key technique for training neural networks without large labeled datasets. This survey categorizes approaches into generative, contrastive, and hybrid methods, analyzing their theoretical foundations, experimental results, and practical applications.',
    tags: ['Self-supervised Learning', 'Contrastive Learning', 'Survey', 'Representation Learning'],
  },
  {
    id: '20',
    type: 'thesis',
    title: 'Explainable Artificial Intelligence in Medical Imaging: Methods, Challenges, and Clinical Applications',
    authors: ['Aisha Patel'],
    venue: 'Stanford University School of Medicine',
    year: 2023,
    citationCount: 218,
    citationTrend: [12, 34, 72, 124, 168, 194, 218],
    abstract: 'This dissertation investigates explainability methods for deep learning models applied to medical image analysis. We develop novel gradient-based attribution methods and evaluate them on clinical datasets including chest X-rays, brain MRI scans, and dermoscopy images.',
    tags: ['Explainable AI', 'Medical Imaging', 'XAI', 'Clinical AI'],
  },
  {
    id: '21',
    type: 'preprint',
    title: 'Mixtral of Experts: A Sparse Mixture-of-Experts Language Model for Efficient Scaling',
    authors: ['Albert Q. Jiang', 'Alexandre Sablayrolles', 'Antoine Roux', 'Arthur Mensch'],
    venue: 'arXiv Preprint',
    year: 2024,
    citationCount: 4120,
    citationTrend: [310, 820, 1600, 2400, 3100, 3700, 4120],
    abstract: 'We introduce Mixtral 8x7B, a sparse mixture-of-experts model. As with Mistral 7B, it speaks English, French, Italian, German and Spanish, and has strong performance in code generation. On most standard benchmarks, Mixtral 8×7B equals or outperforms Llama 2 70B and GPT-3.5.',
    tags: ['Mixture of Experts', 'LLM', 'Efficient AI', 'Scaling'],
  },
  {
    id: '22',
    type: 'book_chapter',
    title: 'Ethics of Artificial Intelligence: Bias, Fairness, and Accountability in Machine Learning Systems',
    authors: ['Kate Crawford', 'Meredith Whittaker', 'Solon Barocas'],
    venue: 'The Oxford Handbook of Ethics of AI — Oxford University Press',
    year: 2020,
    citationCount: 2841,
    citationTrend: [142, 380, 720, 1200, 1780, 2300, 2841],
    abstract: 'This chapter examines the ethical dimensions of artificial intelligence systems, with particular focus on algorithmic bias, fairness definitions, and accountability structures. We analyze how historical patterns of discrimination can be encoded and amplified by machine learning systems trained on biased data.',
    tags: ['AI Ethics', 'Algorithmic Fairness', 'Bias', 'Machine Learning'],
  },
  {
    id: '23',
    type: 'conference_paper',
    title: 'Sora: A Review on Background, Technology, Limitations, and Future Scope',
    authors: ['Yixin Liu', 'Kai Zhang', 'Yuan Li', 'Zhiling Yan', 'Chujie Gao'],
    venue: 'ACM Multimedia 2024',
    year: 2024,
    citationCount: 1892,
    citationTrend: [142, 380, 620, 980, 1280, 1610, 1892],
    abstract: 'We provide a comprehensive review of OpenAI\'s Sora, a text-to-video generation model. We discuss the background of video generation models, technical details of Sora, its limitations, and future directions for text-to-video generation research.',
    tags: ['Text-to-Video', 'Sora', 'Generative AI', 'Video Generation'],
  },
  {
    id: '24',
    type: 'journal_article',
    title: 'Neural Architecture Search: A Survey',
    authors: ['Thomas Elsken', 'Jan Hendrik Metzen', 'Frank Hutter'],
    venue: 'Journal of Machine Learning Research (JMLR)',
    year: 2019,
    citationCount: 6280,
    citationTrend: [410, 920, 1700, 2600, 3800, 5100, 6280],
    abstract: 'Neural architecture search (NAS) is a subfield of AutoML that automates the design of neural network architectures. This survey provides a comprehensive overview of existing NAS methods, categorized according to search space, search strategy, and performance estimation strategy.',
    tags: ['Neural Architecture Search', 'AutoML', 'Hyperparameter Optimization', 'Automation'],
  },
  {
    id: '25',
    type: 'conference_paper',
    title: 'Scaling Laws for Neural Language Models',
    authors: ['Jared Kaplan', 'Sam McCandlish', 'Tom Henighan', 'Tom B. Brown', 'Benjamin Chess'],
    venue: 'ICLR 2020 Workshop',
    year: 2020,
    citationCount: 7810,
    citationTrend: [510, 1200, 2400, 3900, 5200, 6600, 7810],
    abstract: 'We study empirical scaling laws for language model performance on the cross-entropy loss. The loss scales as a power-law with model size, dataset size, and the amount of compute used for training, with some trends spanning more than seven orders of magnitude.',
    tags: ['Scaling Laws', 'Language Models', 'Training Compute', 'Power Laws'],
  },
  {
    id: '26',
    type: 'journal_article',
    title: 'Automated Machine Learning: Methods, Systems, Challenges',
    authors: ['Frank Hutter', 'Lars Kotthoff', 'Joaquin Vanschoren'],
    venue: 'Automated Machine Learning — Springer Nature',
    year: 2019,
    citationCount: 2180,
    citationTrend: [112, 310, 620, 1000, 1480, 1870, 2180],
    abstract: 'With the increasing complexity of machine learning pipelines and the demand for non-expert usage, automated machine learning (AutoML) has become an important research area. This book covers the full stack from hyperparameter optimization to neural architecture search and meta-learning.',
    tags: ['AutoML', 'Hyperparameter Optimization', 'Machine Learning', 'Automation'],
  },
  {
    id: '27',
    type: 'preprint',
    title: 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models',
    authors: ['Jason Wei', 'Xuezhi Wang', 'Dale Schuurmans', 'Maarten Bosma', 'Fei Xia'],
    venue: 'arXiv Preprint',
    year: 2022,
    citationCount: 11240,
    citationTrend: [720, 1800, 3500, 5800, 7900, 9800, 11240],
    abstract: 'We explore how generating a chain of thought—a series of intermediate reasoning steps—significantly improves the ability of large language models to perform complex reasoning. Experiments on three large language models show that chain-of-thought prompting improves performance on a range of arithmetic, commonsense, and symbolic reasoning tasks.',
    tags: ['Chain-of-Thought', 'LLM Reasoning', 'Prompting', 'Large Language Models'],
  },
  {
    id: '28',
    type: 'journal_article',
    title: 'Climate Change and Artificial Intelligence: A Survey of Sustainable Machine Learning',
    authors: ['Emma Strubell', 'Ananya Ganesh', 'Andrew McCallum'],
    venue: 'Environmental Science & Technology',
    year: 2022,
    citationCount: 1821,
    citationTrend: [98, 280, 560, 920, 1280, 1580, 1821],
    abstract: 'We analyze the energy consumption and environmental impact of training large neural networks. Based on measurements of four models in NLP, we estimate the financial and environmental costs of training them and propose concrete recommendations for reducing the carbon footprint of machine learning.',
    tags: ['Green AI', 'Energy Efficiency', 'Carbon Footprint', 'Sustainable ML'],
  },
  {
    id: '29',
    type: 'book_chapter',
    title: 'Transfer Learning in Natural Language Processing: From Feature Extraction to Fine-tuning',
    authors: ['Sebastian Ruder', 'Matthew E. Peters', 'Swabha Swayamdipta', 'Thomas Wolf'],
    venue: 'Proceedings of NAACL-HLT Tutorial',
    year: 2019,
    citationCount: 3820,
    citationTrend: [280, 640, 1200, 1980, 2700, 3300, 3820],
    abstract: 'Transfer learning has revolutionized computer vision, and recent results suggest that natural language processing (NLP) will undergo a similar transformation. This tutorial covers pre-trained word embeddings, ELMo, ULMFiT, OpenAI GPT, BERT, and practical guidelines for applying transfer learning in NLP.',
    tags: ['Transfer Learning', 'NLP', 'Fine-tuning', 'BERT'],
  },
  {
    id: '30',
    type: 'thesis',
    title: 'Multimodal Learning for Scientific Document Understanding',
    authors: ['Riya Sharma'],
    venue: 'Carnegie Mellon University Language Technologies Institute',
    year: 2023,
    citationCount: 412,
    citationTrend: [22, 64, 128, 218, 312, 374, 412],
    abstract: 'This thesis addresses the challenge of understanding scientific documents, which contain complex multimodal information including text, figures, tables, and equations. We develop novel models that jointly process these modalities to support downstream tasks such as document classification, information extraction, and question answering.',
    tags: ['Multimodal Learning', 'Document Understanding', 'Scientific NLP', 'Information Extraction'],
  },
];

export default MOCK_RESULTS;
