import React, { useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Calendar, ExternalLink, Github, Users } from 'lucide-react';
import api from '../../../services/api';

export default function ProjectDetails() {
  const { id } = useParams(); const navigate = useNavigate();
  const { data, isLoading, isError } = useQuery({ queryKey: ['project', id], queryFn: async () => (await api.get(`/projects/${id}`)).data?.data, enabled: !!id });
  const project = data;
  useEffect(() => { if (!project) return; document.title = `${project.title} | Research Connect`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.name = 'description'; document.head.appendChild(meta); } meta.content = (project.description || '').slice(0, 160); }, [project]);
  if (isLoading) return <div className="animate-pulse space-y-4"><div className="h-56 rounded-2xl bg-slate-200"/><div className="h-8 w-1/2 rounded bg-slate-200"/></div>;
  if (isError || !project) return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><h1 className="text-xl font-bold">Project unavailable</h1><button onClick={() => navigate('/projects')} className="mt-4 text-sm font-bold text-blue-600">Back to projects</button></div>;
  return <article className="mx-auto max-w-5xl pb-12"><button onClick={() => navigate('/projects')} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-blue-600"><ArrowLeft size={17}/> All projects</button><header className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="h-40 bg-gradient-to-br from-blue-700 via-indigo-700 to-slate-900"/><div className="p-7"><div className="mb-3 flex flex-wrap gap-2">{project.tags?.map((tag) => <span key={tag} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-600">{tag}</span>)}</div><h1 className="text-3xl font-bold text-slate-900">{project.title}</h1><p className="mt-3 max-w-3xl leading-relaxed text-slate-600">{project.longDescription || project.description}</p></div></header><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_280px]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Research objectives</h2><ul className="mt-4 space-y-3">{project.objectives?.length ? project.objectives.map((item) => <li key={item} className="flex gap-3 text-sm text-slate-600"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-blue-600"/>{item}</li>) : <li className="text-sm text-slate-400">Objectives will be added soon.</li>}</ul><h2 className="mt-8 text-lg font-bold">Collaborators</h2><div className="mt-3 space-y-2">{project.collaborators?.map((member) => <div key={member._id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="text-sm font-semibold">{member.name || member.email}</span><span className="text-xs text-slate-500">{member.role}</span></div>)}</div></section><aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Project status</p><p className="mt-2 text-lg font-bold text-emerald-600">{project.status}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${project.progress || 0}%` }}/></div><p className="mt-1 text-xs text-slate-500">{project.progress || 0}% complete</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 space-y-3"><p className="flex items-center gap-2 text-sm text-slate-600"><Calendar size={16}/> {project.startDate ? new Date(project.startDate).toLocaleDateString() : 'Start date not set'}</p><p className="flex items-center gap-2 text-sm text-slate-600"><Users size={16}/> {project.collaborators?.length || 0} collaborators</p>{project.githubUrl && <a href={project.githubUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-bold text-blue-600"><Github size={16}/> View GitHub <ExternalLink size={13}/></a>}</div></aside></div></article>;
}
